enable timestamps modeling_utils.py
If the reference audio file is longer than 30 seconds, the following error is observed:
```
ValueError: You have passed more than 3000 mel input features (> 30 seconds) which automatically enables long-form generation which requires the model to predict timestamp tokens. Please either pass return_timestamps=True or make sure to pass no more than 3000 mel input features.
```
I don't know if this is the correct way to fix the problem, but it works for me.